### ISSUE TITLE
Test failure on go tip

### ISSUE THREAD

**Issue by dchest** [gorilla/feeds#16]
https://travis-ci.org/gorilla/feeds/jobs/55587220

Diffs between "got" and "expected":

```diff
diff --git a/1.txt b/2.txt
index 4894da0..1f6f674 100644
--- a/1.txt
+++ b/2.txt
@@ -1,4 +1,4 @@
-               <?xml version="1.0" encoding="UTF-8"?><feed>
+               <?xml version="1.0" encoding="UTF-8"?><feed xmlns="http://www.w3.org/2005/Atom">
                  <title>jmoiron.net blog</title>
                  <id>http://jmoiron.net/blog</id>
                  <updated>2013-01-16T21:52:35-05:00</updated>
```

Do you think it's a bug in feeds, tests, or Go? I suspect these changes has something to do with it: 
 * https://github.com/golang/go/commit/3be158d6ab73090a74df6bc3b7cfa062d896483a?diff=unified   
 * https://go-review.googlesource.com/#/c/5910/

**Comment by kisielk** [comment]
Sorry for taking so long to get to this, I've kind of neglected the feeds package....

This is because Go 1.5 / tip now supports the xmlns attribute.

**Comment by kisielk** [comment]
Not sure of the best way to fix it, short of doing a proper XML diff and ignoring that element, or writing different tests for 1.5. Or not testing on 1.4 and earlier (which seems like a bit premature...)

**Comment by elithrar** [comment]
I think just going for separate tests (via `runtime.Version()` or using
build flags) will probably do. Pre 1.4 builds are likely to be around for a
while in most current Linux distros (Ubuntu 15.04 is 1.3.1) so we should
try to keep it around. I'll take a look at updating the test shortly.

**Comment by kisielk** [comment]
The weird thing is tests seem to be passing now with the go1.5 Rc...

**Comment by elithrar** [comment]
That'd be due to this: https://github.com/golang/go/commit/c0d6d332f68a38bc13825279d2048a16fffe87f9

Hence you can probably close it until we see a update to https://github.com/golang/go/issues/11841

**Comment by kisielk** [comment]
Ah I see, makes sense. I haven't been following the XML story in encoding/xml since I've mostly been using  https://github.com/beevik/etree

Good to know they're going to take a serious look at it though.
