### ISSUE TITLE
Format characters in field "Description" are causing problems

### ISSUE THREAD

**Issue by oliver006** [gorilla/feeds#18]
If I use a string in `Item.Description` that contains format strings like `%s` the output is broken, looks like something is trying to sprintf the description string

```
    &Item{
        Title:       "Limiting Concurrency in Go",
        Link:        &Link{Href: "http://jmoiron.net/blog/limiting-concurrency-in-go/"},
        
 -->    Description: "abcdee %s deeefffff",
        
        Author:      &Author{"Jason Moiron", "jmoiron@jmoiron.net"},
        Created:     now,
    },
```
in the RSS feed content is `abcdee %!s(MISSING) deeefffff`.
Real-world example for this would be urlencoded links.
Any suggestions as to what I can do to prevent the formatting to happen?

**Comment by kisielk** [comment]
I added a test for this case in the above-mentioned commit and couldn't reproduce. If you are still able to reproduce the problem, please provide a test case.
