### ISSUE TITLE
Fails W3C feed checker

### ISSUE THREAD

**Issue by kaihendry** [gorilla/feeds#26]
<img src=http://s.natalian.org/2015-10-09/1444370397_1918x1058.png>

https://validator.w3.org/feed/check.cgi

Would be nice if the example outputs were raw files in the repo so they could be referenced by URL to various RSS feed checkers.

**Comment by netroby** [comment]
```

line 1, column 169: pubDate must be an RFC-822 date-time: 22 Nov 15 06:27 UTC [help]
... description><pubDate>22 Nov 15 06:27 UTC</pubDate><item><title>Hello a t ...
```

**Comment by netroby** [comment]
see http://www.rssboard.org/rss-profile#data-types-datetime

**Comment by netroby** [comment]
https://validator.w3.org/feed/docs/error/InvalidRFC2822Date.html

**Comment by tomkwok** [comment]
For reference:
https://github.com/kabukky/journey/issues/60
https://github.com/kabukky/feeds/commits/master

**Comment by gshilin** [comment]
There is also the following message:

> This feed is valid, but interoperability with the widest range of feed readers could be improved by implementing the following recommendations.
>
> line 16, column 2: Missing atom:link with rel="self"  [[Help](https://validator.w3.org/feed/docs/warning/MissingAtomSelfLink.html)]

**Comment by AlexanderMatveev** [comment]
Up, W3C still not validating
