### ISSUE TITLE
Description = body?

### ISSUE THREAD

**Issue by kaihendry** [gorilla/feeds#34]
I'm a bit confused by the API. Is Description for the body of the blog post?

**Comment by elithrar** [comment]
https://godoc.org/github.com/gorilla/feeds#Item

`    Description string // used as description in rss, summary in atom`

(It depends on the output format)

**Comment by kaihendry** [comment]
Thanks, I guess what confuses me is the best practice when it comes to feeding the description or the entire body of the blog in the RSS feed. It seems most people prefer to put the whole blog in the feed for easy reading.

**Comment by elithrar** [comment]
Yep, that's totally up to you :)
