### ISSUE TITLE
content type="html"

### ISSUE THREAD

**Issue by kaihendry** [gorilla/feeds#35]
Is there a content type "markdown" since it seems silly to publish as html and then read by newsbeuter which gets it back down into markdown style.

**Comment by elithrar** [comment]
"type" is part of the RSS spec, and needs to be standard MIME type: https://cyber.harvard.edu/rss/rss.html

Most outputs won't support Markdown, whereas newsbeuter is designed to convert from HTML.

**Comment by elithrar** [comment]
(closing, but let me know if any other questions)
