### ISSUE TITLE
Category is missing in Rss Feed

### ISSUE THREAD

**Issue by Cyash** [gorilla/feeds#51]
Category Field was missing from Rss feed, I've added support for it, If there is interest I could submit a pull request.
![rssfeed_category](https://user-images.githubusercontent.com/23339145/41681700-73622b16-74a3-11e8-8f63-fa6ac8154c90.PNG)

**Comment by robjloranger** [comment]
I can take this up, I was just looking at adding categories for an RSS feed.

**Comment by robjloranger** [comment]
the interesting part would be properly supported multiple category elements on one item as all the feed specs allow for.
