### ISSUE TITLE
Sort feed items by created timestamp

### ISSUE THREAD

**Issue by dewey** [gorilla/feeds#54]
I have a use case where the items have the correct created timestamp but I get them as an unordered list. Would it make sense to include a helper function to sort the items in a feed by a key or would that be out of scope?

The use case would be to apply this before calling `ToRss()` if needed.

**Comment by kisielk** [comment]
I could see that being useful. Something with a signature like

`func (f *Feed) Sort(func(i, j *Item))`

would be sufficiently generic while still providing some convenience over just using `sort.Slice`.

**Comment by dewey** [comment]
Sounds good, is this something you are going to add or is a PR preferred?

**Comment by kisielk** [comment]
If you can put together a PR with some tests, that would be great :)

**Comment by dewey** [comment]
Not sure why it's not linked here, but I just submitted the PR. https://github.com/gorilla/feeds/pull/55

**Comment by kisielk** [comment]
I had some time so I implemented the `Sort` function as discussed. I used your tests to verify. Thanks for the suggestion and providing the tests!

**Comment by dewey** [comment]
Thanks for the quick fix, I wasn't aware of the way you are doing it but it's quite elegant. Learned something new!
