### ISSUE TITLE
problems unmarshaling rss

### ISSUE THREAD

**Issue by Athulus** [gorilla/feeds#58]
I am trying to use feeds to combine multiple rss feeds

I've found 2 problems trying to unmarshal rss feeds so far

- the `rssFeedXml` struct is private so i cannot unmarshal the base XML

- after recreating the `rssFeedXml` struct locally the Items slice is always nil. This can be fixed by adding an xml tag. this is a similar problem to #36
```
Items          []*RssItem `xml:"item"`
```

 

Would I be welcome to submit a PR with these changes? Or, is this library only intended for feed creation?

**Comment by kisielk** [comment]
This library has been designed with generating feeds in mind, not many provisions have been made for consuming feeds. That being said, I'm not against adding the ability to consume feeds but it probably needs a bit more planning and work than just making the structs public and adding some tags.

If you want to work on that kind of functionality and incorporate it into this library, I'd be open to having it included.

**Comment by Athulus** [comment]
Can you expand on what the other work would be for consuming feeds? I was able to get  an rss files into an rssFeedXml object with the changes I mentioned and using the standard `xml.Unmarshal` method

Do you mean converting the specific feed structs back into the generic feed format? I agree that it would make sense to do that if you wanted to fully support consuming and translating between different types of feeds.

**Comment by Athulus** [comment]
closed with #59
