### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by falzm** [gorilla/feeds#69]
Hi,

It would be nice if you could release a new tagged version of this package, since using it with Go modules will automatically pull the latest tagged version instead of `master` – and the latest release is [more than 1 year old with 15 commits pushed since](https://github.com/gorilla/feeds/compare/v1.1.0...master).

🙏😇

**Comment by elithrar** [comment]
See https://github.com/gorilla/feeds/releases/tag/v1.1.1

Note that the changes are _very_ minor - time between releases is not a great measure of whether a release is needed 😉

**Comment by falzm** [comment]
Thank you for taking the time 👍
