### ISSUE TITLE
Itunes Podcast Tags

### ISSUE THREAD

**Issue by mitchdennett** [gorilla/feeds#70]
Any thoughts on adding support for the itunes rss podcast tags ?

**Comment by elithrar** [comment]
Happy to accept a non-breaking PR, but no direct plans to do so.

**Comment by mitchdennett** [comment]
Awesome, I've made a start on a PR but want to make sure I'm heading in the right direction. Would someone mind taking a look?

**Comment by mitchdennett** [comment]
#71
