### ISSUE TITLE
RSS feeds where items have author tags aren't valid

### ISSUE THREAD

**Issue by Bios-Marcel** [gorilla/feeds#85]
**Describe the bug**

When generating an RSS feeds where the Items have an author, instead of using the `Email`-field, it uses just the `Name` field. This causes the feed to not be readable by most readers, as it doesn't follow the spec.

See: https://www.w3schools.com/XML/rss_tag_author.asp
Also: http://validator.w3.org/feed/

**Steps to Reproduce**
Make a feed with a single item that has an author field and export as RSS

**Expected behavior**

Instead it should've put the `Email` into the `<author>` tag.

**Comment by Bios-Marcel** [comment]
Not stale, duh.

**Comment by yktoo** [comment]
Dear maintainers, can you please reopen this and eventually merge #88? It's a shame this — quite obvious — problem gets ignored and the work done by @Bios-Marcel neglected.

**Comment by Bios-Marcel** [comment]
I just moved on to using my work 🤷 

If projects aren't actively maintained anymore, this'll happen again and again and just be frustrating. gorilla projects generally seem to suffer from this. It's sad, but it is what it is.

Feel free to use my fork as well. If you find issues, i'll try looking into it.
