### ISSUE TITLE
[feature] Support JSON feed v1.1

### ISSUE THREAD

**Issue by binyamin** [gorilla/feeds#91]
**Is your feature request related to a problem? Please describe.**
[The JSON feed spec is currently at v1.1](https://jsonfeed.org/version/1.1). The changes from v1.0 to v1.1 are very minor, so this should be a pretty easy box to check off.

**Describe the solution you'd like**
Here's a synopsis of changes, taken from the specification:
> **Version 1.1 — 8/7/2020:**
>- Updated to use more specific `application/feed+json` MIME type.
>- Added `authors` field to allow more than 1 author per feed or item. Deprecated `author`.
>- Added `language` field.
>- Clarified that `id` should be a string.
>- Updated links to JSON and other specs.

**Comment by hacdias** [comment]
I see @jlelse forked it and implemented it: https://github.com/jlelse/feeds

**Comment by hacdias** [comment]
It is _not_ stale.

**Comment by geira** [comment]
I see JSON feed is a spec, but is it a community accepted standard? Has it been adopted by any recognized standards body, e.g. W3C? Although it is lacking many essenial feaures like official extension namespaces (e.g. Dublin Core) I'm sure it could be useful for many, but currently it only looks like a private initiative without much market traction.

**Comment by s3rj1k** [comment]
> I see JSON feed is a spec, but is it a community accepted standard? Has it been adopted by any recognized standards body, e.g. W3C? Although it is lacking many essenial feaures like official extension namespaces (e.g. Dublin Core) I'm sure it could be useful for many, but currently it only looks like a private initiative without much market traction.

If so, support of version 1.0 should be dropped from package
