### ISSUE TITLE
[feature] Allow multiple Links in a feed item

### ISSUE THREAD

**Issue by ratzrattillo** [gorilla/feeds#98]
**Is your feature request related to a problem? Please describe.**

I would like to have the option to add multiple links to a feed item

**Describe the solution you'd like**

The Link property of a feed should rather be an array of Links. Similar like here:
https://github.com/gorilla/feeds/compare/master...ratzrattillo:feeds:master

**Describe alternatives you've considered**

I have the following workaround in place just for Atom Feeds (However i am not a good Go programmer)

**Comment by meblum** [comment]
I don't think that the rss specification allows for more than one link. When adding two `link` elements [validation](https://validator.w3.org/feed/check.cgi) fails.

**Comment by weberc2** [comment]
This would be useful for Atom feeds as it would allow pagination. https://stackoverflow.com/questions/1301392/pagination-in-feeds-like-atom-and-rss

As a workaround we could munge the output XML and add our own link tag, but that's really disappointing from a performance and usability perspective.

**Comment by jaitaiwan** [comment]
I'll take a look, if you're saying it's part of the Atom spec, then this library purports to support it.

**Comment by jaitaiwan** [comment]
So far as I can tell, the `AtomFeed` structure already supports what you'd like. I'm going to close this out, but if have a concrete example of how this doesn't work please let me know. Unfortunately it's been some time since this issue was opened and since then, the original link no longer works for me to review it.
